### ISSUE TITLE
Difference between the ver.

### ISSUE THREAD

**Issue by Sindeg** [Dexious/Al_Rayak_Lib0924_Dex#1]
Hey, found 5 different mission files. What is the difference between them ?

Al_Rayak_Lib0924_Dex_TFAR_r2.pja310.pbo
Al_Rayak_Lib0924_Dex_TFAR_r3.pja310.pbo
Al_Rayak_Lib0924_Dex_r1.pja310.pbo  
Al_Rayak_Lib0924_Dex_r2.pja310.pbo  
Al_Rayak_Lib0924_Dex_r3.pja310.pbo

**Comment by Dexious** [comment]
Version with highier "r#" is the latest without Task Force Radio.
Version with highier "TFAR_r#" is the latest with Task Force Radio.

The main difference between the versions are some custom placed areas like Military bases as Objectives.

I keep the other versions there for Archive.
